apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lab2frontend
  name: lab2frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab2frontend
  template:
    metadata:
      labels:
        app: lab2frontend
    spec:
      containers:
      - image: public.ecr.aws/w4e1v2x6/qa-wfl/qakf/sfe:v1
        name: sfe
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
