apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: git-web
  name: git-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: git-web
  strategy: {}
  template:
    metadata:
      labels:
        app: git-web
    spec:
      containers:
      - image: nginx
        name: git-web
        volumeMounts:
        - name: git-vol
          mountPath: /usr/share/nginx/
      - name: git-sync
        image: k8s.gcr.io/git-sync:v3.1.6
        volumeMounts:
          - name: git-vol
            mountPath: /tmp/git
        env:
          - name: GIT_SYNC_REPO
            value: https://github.com/qalearning/qakf-sidecar-lab.git
          - name: GIT_SYNC_BRANCH
            value: main
          - name: GIT_SYNC_DEPTH
            value: "1"
          # - name: GIT_SYNC_ROOT
          #   value: "/tmp/git"
          - name: GIT_SYNC_DEST
            value: "html"
      volumes:
      - name: git-vol
        emptyDir: {}
