apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - image: public.ecr.aws/w4e1v2x6/qa-wfl/qakf/sfe:v1
    name: frontend
    imagePullPolicy: Always
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
